[WIP] CPLAT-11724 Add missing fields to some SyntheticEvent classes
Workiva/react-dart pull request #304
Opened 2021-02-09 20:54 UTC by aaronlademann-wf

...

2021-02-09 20:55 UTC, aviary-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2021-02-09 20:56 UTC, semveraudit-wf commented
### Public API Changes

 Recommendation: **:warning: Minor version bump**


```diff
@@ line 720: package:react/src/react_client/event_helpers.dart @@
-  SyntheticWheelEvent createSyntheticWheelEvent({SyntheticWheelEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, num deltaX, num deltaMode, num deltaY, num deltaZ})
+  SyntheticWheelEvent createSyntheticWheelEvent({SyntheticWheelEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, num deltaX, num deltaMode, num deltaY, num deltaZ, num detail, dynamic view, bool Function(String) getModifierState})
// `detail` was added.
// Adding an optional parameter is a minor change.
```

```diff
@@ line 475: package:react/src/react_client/event_helpers.dart @@
-  SyntheticPointerEvent createSyntheticPointerEvent({SyntheticPointerEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, num pointerId, num width, num height, num pressure, num tangentialPressure, num tiltX, num tiltY, num twist, String pointerType, bool isPrimary})
+  SyntheticPointerEvent createSyntheticPointerEvent({SyntheticPointerEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, num pointerId, num width, num height, num pressure, num tangentialPressure, num tiltX, num tiltY, num twist, String pointerType, bool isPrimary, num detail, dynamic view, bool Function(String) getModifierState})
// `detail` was added.
// Adding an optional parameter is a minor change.
```

```diff
@@ line 328: package:react/src/react_client/event_helpers.dart @@
-  SyntheticFocusEvent createSyntheticFocusEvent({SyntheticFocusEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, dynamic relatedTarget})
+  SyntheticFocusEvent createSyntheticFocusEvent({SyntheticFocusEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, dynamic relatedTarget, num detail, dynamic view})
// `detail` was added.
// Adding an optional parameter is a minor change.
```

```diff
@@ line 534: package:react/src/react_client/event_helpers.dart @@
-  SyntheticTouchEvent createSyntheticTouchEvent({SyntheticTouchEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, bool altKey, dynamic changedTouches, bool ctrlKey, bool metaKey, bool shiftKey, dynamic targetTouches, dynamic touches})
+  SyntheticTouchEvent createSyntheticTouchEvent({SyntheticTouchEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, bool altKey, dynamic changedTouches, bool ctrlKey, bool metaKey, bool shiftKey, dynamic targetTouches, dynamic touches, num detail, dynamic view, bool Function(String) getModifierState})
// `detail` was added.
// Adding an optional parameter is a minor change.
```

```diff
@@ line 408: package:react/src/react_client/event_helpers.dart @@
-  SyntheticMouseEvent createSyntheticMouseEvent({SyntheticMouseEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, bool altKey, num button, num buttons, num clientX, num clientY, bool ctrlKey, dynamic dataTransfer, bool metaKey, num pageX, num pageY, dynamic relatedTarget, num screenX, num screenY, bool shiftKey})
+  SyntheticMouseEvent createSyntheticMouseEvent({SyntheticMouseEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, bool altKey, num button, num buttons, num clientX, num clientY, bool ctrlKey, dynamic dataTransfer, bool metaKey, num pageX, num pageY, dynamic relatedTarget, num screenX, num screenY, bool shiftKey, num detail, dynamic view, bool Function(String) getModifierState})
// `detail` was added.
// Adding an optional parameter is a minor change.
```
<details>
<summary>Click to see 8 more API Changes</summary><p>

---
```diff
@@ line 226: package:react/src/react_client/event_helpers.dart @@
-  SyntheticKeyboardEvent createSyntheticKeyboardEvent({SyntheticKeyboardEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, bool altKey, String char, bool ctrlKey, String locale, num location, String key, bool metaKey, bool repeat, bool shiftKey, num keyCode, num charCode})
+  SyntheticKeyboardEvent createSyntheticKeyboardEvent({SyntheticKeyboardEvent baseEvent, bool bubbles, bool cancelable, dynamic currentTarget, bool defaultPrevented, void Function() preventDefault, void Function() stopPropagation, num eventPhase, bool isTrusted, dynamic nativeEvent, dynamic target, num timeStamp, String type, bool altKey, String char, bool ctrlKey, String locale, num location, String key, bool metaKey, bool repeat, bool shiftKey, num keyCode, num charCode, num detail, dynamic view, bool Function(String) getModifierState})
// `detail` was added.
// Adding an optional parameter is a minor change.
```

```diff
@@ line 266: package:react/src/react_client/synthetic_event_wrappers.dart @@
class SyntheticFocusEvent extends SyntheticEvent
+     dynamic get view
//    Adding a field is a minor change.

+     num get detail
//    Adding a field is a minor change.

```

```diff
@@ line 10: package:react/src/react_client/synthetic_data_transfer.dart @@
class SyntheticDataTransfer
-     SyntheticDataTransfer SyntheticDataTransfer(String dropEffect, String effectAllowed, List<dynamic> files, List<String> types)
+     SyntheticDataTransfer SyntheticDataTransfer(String dropEffect, String effectAllowed, List<dynamic> files, List<String> types, {DataTransferItemList items})
//    `items` was added.
//    Adding an optional parameter is a minor change.

+     DataTransferItemList get items
//    Adding a field is a minor change.

```

```diff
@@ line 175: package:react/src/react_client/synthetic_event_wrappers.dart @@
class SyntheticKeyboardEvent extends SyntheticEvent
+     String get code
//    Adding a field is a minor change.

+     num get which
//    Adding a field is a minor change.

+     num get detail
//    Adding a field is a minor change.

+     bool getModifierState(String key)
//    Adding a method is a minor change.

+     dynamic get view
//    Adding a field is a minor change.

```

```diff
@@ line [...]

2021-02-09 21:11 UTC, aaronlademann-wf commented on test/react_client/event_helpers_test.dart
> +                    : isFalse);
Changes like this are necessary since `SyntheticKeyboardEvent` extends from `SyntheticUIEvent`.

2021-02-11 22:15 UTC, sydneyjodon-wk commented on lib/src/react_client/event_helpers.dart
> +    'getModifierState': nativeEvent.getModifierState,
Same question for `createSyntheticKeyboardEvent`

2021-02-11 22:15 UTC, sydneyjodon-wk commented on lib/src/react_client/event_helpers.dart
> +    'getModifierState': nativeEvent.getModifierState,
Same question for `createSyntheticPointerEvent` and `createSyntheticWheelEvent`

2021-02-11 22:15 UTC, sydneyjodon-wk commented on test/react_client/event_helpers_test.dart
> +      });
Why do none of the `SyntheticKeyboardEvent` tests in this file check `code` and `which`?

2021-02-11 22:15 UTC, sydneyjodon-wk commented on test/react_client/event_helpers_test.dart
> +      });
Why do only some of the `SyntheticMouseEvent` tests in this file check `movementX` and `movementY`?

2021-02-25 20:31 UTC, greglittlefield-wf requested changes

2021-02-25 20:31 UTC, greglittlefield-wf commented on lib/src/react_client/synthetic_data_transfer.dart
> +  static final _emptyDataTransferItemList = DataTransfer().items;
We should create this object every time since it's mutable

2021-11-01 17:35 UTC, closed without merging